"""add session title

Revision ID: 253c95eeb5b1
Revises: 45d59b669b7a
Create Date: 2026-09-29 20:18:20.944711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253c95eeb5b1'
down_revision: Union[str, Sequence[str], None] = '45d59b669b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "sessions",
    sa.Column(
        "title",
        sa.String(length=255),
        nullable=False,
        server_default="New Chat",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ###
